-- Migration V11: Đồng bộ dữ liệu Hồ sơ Loyalty, Banners, Flash Sale, Nhập kho & Đổi trả theo UI KickVerse Frontend

-- 1. Bổ sung trường Tích điểm & Hạng thành viên Loyalty cho bảng users
ALTER TABLE users ADD COLUMN tier VARCHAR(20) NOT NULL DEFAULT 'BRONZE';
ALTER TABLE users ADD COLUMN points INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN total_spent NUMERIC(19, 2) NOT NULL DEFAULT 0.00;

-- 2. Bảng quản lý Banners & Carousel Trang Chủ
CREATE TABLE banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    subtitle VARCHAR(150),
    image_url VARCHAR(255) NOT NULL,
    cta_link VARCHAR(255) NOT NULL DEFAULT '/shop',
    display_order INT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. Bảng quản lý Chiến dịch Flash Sale
CREATE TABLE flash_sale_campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    discount_pct VARCHAR(50),
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'UPCOMING', -- UPCOMING, ACTIVE, ENDED
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE flash_sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL,
    product_variant_id BIGINT NOT NULL,
    special_price NUMERIC(19, 2) NOT NULL,
    allocated_stock INT NOT NULL DEFAULT 10,
    sold_count INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_flash_items_campaign FOREIGN KEY (campaign_id) REFERENCES flash_sale_campaigns(id) ON DELETE CASCADE,
    CONSTRAINT fk_flash_items_variant FOREIGN KEY (product_variant_id) REFERENCES product_variants(id) ON DELETE CASCADE
);

-- 4. Bảng phiếu Nhập Kho Tồn Kho (Inventory Stock Receipts)
CREATE TABLE stock_import_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_variant_id BIGINT NOT NULL,
    sku VARCHAR(50) NOT NULL,
    quantity INT NOT NULL,
    import_unit_price NUMERIC(19, 2) NOT NULL,
    supplier_name VARCHAR(150) NOT NULL,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    CONSTRAINT fk_import_receipts_variant FOREIGN KEY (product_variant_id) REFERENCES product_variants(id)
);

-- 5. Bảng Quản Lý Yêu Cầu Đổi / Trả Hàng (Return & Refund Requests)
CREATE TABLE return_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_no VARCHAR(50) NOT NULL UNIQUE,
    order_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    reason_code VARCHAR(50) NOT NULL, -- SIZE_FIT, DEFECT, WRONG_ITEM
    reason_note TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED, COMPLETED
    reviewed_at TIMESTAMP WITH TIME ZONE,
    reviewed_by VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_return_requests_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_return_requests_user FOREIGN KEY (user_id) REFERENCES users(id)
);
