CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    address_id BIGINT, -- Chỉ để tham chiếu lịch sử, địa chỉ chính được snapshot bên dưới
    receiver_name VARCHAR(100) NOT NULL,
    phone VARCHAR(10) NOT NULL CONSTRAINT chk_order_phone CHECK (phone ~ '^[0-9]{10}$'),
    province VARCHAR(100) NOT NULL,
    district VARCHAR(100) NOT NULL,
    ward VARCHAR(100) NOT NULL,
    address_detail VARCHAR(255) NOT NULL,
    coupon_id BIGINT,
    order_no VARCHAR(50) NOT NULL UNIQUE,
    total_amount NUMERIC(19, 2) NOT NULL,
    shipping_fee NUMERIC(19, 2) NOT NULL DEFAULT 0.00,
    discount NUMERIC(19, 2) NOT NULL DEFAULT 0.00,
    final_amount NUMERIC(19, 2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING', -- PENDING, CONFIRMED, PREPARING, SHIPPING, DELIVERED, CANCELLED, REFUNDED
    payment_status VARCHAR(30) NOT NULL DEFAULT 'PENDING', -- PENDING, PAID, FAILED, REFUNDED
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100),
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_orders_coupon FOREIGN KEY (coupon_id) REFERENCES coupons(id)
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    variant_id BIGINT, -- Nullable phòng khi variant bị xóa khỏi catalog
    product_name VARCHAR(150) NOT NULL, -- Snapshot
    variant_sku VARCHAR(50) NOT NULL,  -- Snapshot
    color VARCHAR(50),                  -- Snapshot
    size VARCHAR(20),                   -- Snapshot
    price NUMERIC(19, 2) NOT NULL,      -- Snapshot giá lúc mua
    quantity INT NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_variant FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE SET NULL
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    method VARCHAR(30) NOT NULL, -- COD, VNPAY, MOMO...
    transaction_id VARCHAR(100),
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING', -- PENDING, SUCCESS, FAILED
    paid_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);

-- Thêm Foreign Key từ coupon_usages sang orders
ALTER TABLE coupon_usages ADD CONSTRAINT fk_usages_order FOREIGN KEY (order_id) REFERENCES orders(id);
