CREATE TABLE refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    reason VARCHAR(255),
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED, COMPLETED
    processed_by BIGINT, -- Admin xử lý
    processed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_refunds_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_refunds_processor FOREIGN KEY (processed_by) REFERENCES users(id)
);

CREATE TABLE stock_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id BIGINT NOT NULL,
    type VARCHAR(30) NOT NULL, -- IMPORT, EXPORT, ADJUSTMENT, ORDER_RESERVE, ORDER_RELEASE
    quantity INT NOT NULL,
    reference_id BIGINT, -- Có thể là order_id hoặc id của phiếu nhập/xuất kho
    note VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stock_tx_variant FOREIGN KEY (variant_id) REFERENCES product_variants(id)
);
